version: '3.9'

services:

  nasa_service:
    restart: on-failure
    container_name: nasa_service
    build: nasa_service/
    ports:
      - "8001:80"

  star_service:
    restart: on-failure
    container_name: star_service
    build: star_service/
    ports:
      - "8000:80"
